name: nginx-proxy

on:
  push:
    branches:
      - main
    paths:
      - './**'
  
jobs:
  deploy:
    name: Deploy to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v4
        with: 
          images: 13angs/nginx-proxy

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: 13angs/nginx-proxy:latest
          labels: ${{ steps.meta.outputs.labels }}